name: Deploy Code to Github Pages
on:
  workflow_dispatch:
  push:
    branches: 
      - main
jobs:
  build:
    name: Push to Github Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Workflow dispatch event that pushes the current version to the release branch.
      # From here the secondary production deployment workflow will trigger to build the dependencies.
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: sample-version2
          clean: false
          single-commit: true
